name: Publish Packages

on:
  push:
    branches:
      - main
      - "releases/**"
    # tags:
    #   - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish ironPot42.Extensions
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: ./ironPot42.Extensions/ironPot42.Extensions.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}
